# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='baseurl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='main_colour',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
