# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta', '0004_auto_20180511_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=60)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='photo',
            name='comments',
            field=models.ManyToManyField(to='insta.comments'),
        ),
    ]
