# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20180511_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
    ]
